version: 2
updates:
  # Frontend dependencies (npm)
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 2
    groups:
      dev-dependencies:
        dependency-type: 'development'
        patterns:
          - '*'
      production-dependencies:
        dependency-type: 'production'
        patterns:
          - '*'

  # Rust dependencies (Cargo)
  - package-ecosystem: 'cargo'
    directory: '/src-tauri'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 1

  # GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'monthly'
    open-pull-requests-limit: 1
